name: Publish Action

on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  publish-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Enable Corepack
        working-directory: ${{ inputs.cwd }}
        run: corepack enable

      - name: Install Deps and Build
        run: pnpm install
      - run: pnpm build

      - name: Push to Major Version Tag
        uses: teunmooij/github-versioned-release@v1
        with:
          template: "javascript-action"
        env:
          GITHUB_TOKEN: ${{ github.token }}
